Repository kubeflow/code-intelligence, pull requests merged in 2019-08, with the labels that each got.

#28 Utility that allows for Pandas.DataFrame -> Embedding Matrix in Batch
  Issue-Embeddings/flask_app/inference.py
  Issue-Embeddings/notebooks/04b_Inference-Batch.ipynb
Labels: size/XL

#21 Add scraping issues entry point
  Issue-Embeddings/notebooks/Get-GitHub-Issues.ipynb
  Label-Microservice/issue_label_bot.yaml
  Label-Microservice/notebooks/Issues_Loader.ipynb
  Label-Microservice/notebooks/embeddings.py
  Label-Microservice/notebooks/inference.py
  Label-Microservice/requirements.txt
Labels: approved, lgtm, size/XL

#20 Add a notebook to create entry point for training models
  Label-Microservice/notebooks/Label_k8s_issues_with_MLP.ipynb
  Label-Microservice/notebooks/Repo_MLP.ipynb
  Label-Microservice/notebooks/mlp.py
  Label-Microservice/notebooks/repo_config.py
  Label-Microservice/requirements.txt
  Label-Microservice/tests/test_mlp.py
  Label-Microservice/tests/unit.sh
Labels: approved, lgtm, size/XXL

#31 add training pipeline
  Label-Microservice/notebooks/Training_Pipeline.ipynb
  Label-Microservice/notebooks/issues_loader.ipynb
  Label-Microservice/notebooks/repo_mlp.ipynb
  Label-Microservice/requirements.txt
Labels: approved, lgtm, size/XL

#30 Speedup Inference (to get Embeddings for training & new repo on-boarding) by 10x
  Issue-Embeddings/flask_app/inference.py
  Issue-Embeddings/notebooks/04b_Inference-Batch.ipynb
Labels: approved, cla: yes, lgtm, size/L

#32 Collect stats about issues to triage.
  .gitignore
  py/code_intelligence/graphql.py
  py/code_intelligence/test_data/issues_for_triage.json
  py/code_intelligence/triage.ipynb
  py/code_intelligence/triage.py
  py/code_intelligence/triage_test.py
  py/code_intelligence/util.py
Labels: approved, cla: yes, lgtm, size/XXL

#35 Check in the inference code with batching.
  Label-Microservice/notebooks/Training_Pipeline.ipynb
  Label-Microservice/notebooks/inference.py
Labels: approved, cla: yes, lgtm, size/L

#40 Code organization for label microservice
  Label_Microservice/issue_label_bot.yaml
  Label_Microservice/notebooks/issues_loader.ipynb
  Label_Microservice/notebooks/repo_mlp.ipynb
  Label_Microservice/scripts/unit.sh
  Label_Microservice/tests/test_mlp.py
  py/code_intelligence/embeddings.py
  py/code_intelligence/inference.py
  py/label_microservice/__init__.py
  py/label_microservice/mlp.py
  py/label_microservice/repo_config.py
Labels: approved, cla: yes, lgtm, size/M

#38 Add pagination for issue timeline items.
  Issue_Triage/notebooks/triage.ipynb
  py/issue_triage/triage.py
Labels: approved, cla: yes, lgtm, size/XXL

#41 Add worker class to address events in pubsub
  Label_Microservice/notebooks/repo_mlp.ipynb
  Label_Microservice/requirements.txt
  Label_Microservice/tests/test_mlp.py
  Label_Microservice/tests/test_worker.py
  py/code_intelligence/embeddings.py
  py/code_intelligence/github_app.py
  py/code_intelligence/github_util.py
  py/label_microservice/mlp.py
  py/label_microservice/repo_config.py
  py/label_microservice/worker.py
Labels: approved, cla: yes, lgtm, size/XL

#42 Store model artifacts while training models
  Label_Microservice/notebooks/repo_mlp.ipynb
  Label_Microservice/requirements.txt
Labels: approved, cla: yes, lgtm, size/M

#43 Clean up RepoConfig
  py/label_microservice/repo_config.py
Labels: approved, cla: yes, lgtm, size/M

#45 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, cla: yes, lgtm, size/XS

#44 Add exception handling to worker.py
  py/label_microservice/worker.py
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#46 Add files to configure the label microservice
  Label_Microservice/deployment/Dockerfile.worker
  Label_Microservice/deployment/README.md
  Label_Microservice/deployment/deployments-test.yaml
  Label_Microservice/deployment/deployments.yaml
  Label_Microservice/scripts/bootstrap
  Label_Microservice/scripts/bootstrap_test
Labels: approved, cla: yes, lgtm, size/L
