Repository kubeflow/code-intelligence, pull requests merged in 2019-07, with the labels that each got.

#6 added https support
  Issue-Embeddings/deployment/certificate-gh-issue-labeler-com.yaml
  Issue-Embeddings/deployment/certificate.gh-issue-labeler-com.yaml
  Issue-Embeddings/deployment/ingress.yaml
  Issue-Embeddings/notebooks/09_LangModel_API_Demo.ipynb
Labels: approved, size/M

#7 Change endpoint of microservice to embeddings.gh-issue-labeler.com
  Issue-Embeddings/deployment/certificate-gh-issue-labeler-com.yaml
  Issue-Embeddings/deployment/ingress.yaml
  Issue-Embeddings/notebooks/09_LangModel_API_Demo.ipynb
Labels: size/S

#1 add a notebook for MLP classifier
  Issue-Label-Bot-v2/notebooks/Label_k8s_issues_with_MLP.ipynb
  Issue-Label-Bot-v2/requirements.txt
Labels: approved, lgtm, size/XXL

#8 added landing page
  Issue-Embeddings/flask_app/app.py
  Issue-Embeddings/flask_app/templates/index.html
Labels: approved, lgtm, size/M

#10 Update API Notebook
  Issue-Embeddings/notebooks/09_LangModel_API_Demo.ipynb
Labels: approved, lgtm, size/M

#13 Create a simple python program to mark notifications as read.
  notifications/notifications.py
Labels: approved, lgtm, size/M

#14 Get Issue Data
  Issue-Embeddings/flask_app/inference.py
  Issue-Embeddings/notebooks/Get-GitHub-Issues.ipynb
  README.md
Labels: approved, size/L

#15 Fetch GitHub issues and associated comments using GraphQL
  .gitignore
  notifications/notifications.py
  notifications/notifications_test.py
  notifications/test_data/issue-results-test-data.json
  py/code_intelligence/__init__.py
  py/code_intelligence/graphql.py
Labels: approved, lgtm, size/L

#22 Create a python script to triage issues
  .github/issue_label_bot.yaml
  notifications/notifications.py
  py/code_intelligence/graphql.py
  py/code_intelligence/test_data/issues_for_triage.json
  py/code_intelligence/triage.ipynb
  py/code_intelligence/triage.py
  py/code_intelligence/triage_test.py
  py/code_intelligence/util.py
  py/requirements.txt
Labels: approved, lgtm, size/XL

#23 Reorganize modules under code_intelligence.
  .gitignore
  README.md
  py/code_intelligence/notifications.py
  py/code_intelligence/notifications_test.py
  py/code_intelligence/test_data/issue-results-test-data.json
  py/code_intelligence/triage.py
Labels: approved, lgtm, size/M

#27 added package files
  py/Pipfile
  py/Pipfile.lock
  py/code_intelligence/graphql.py
Labels: approved, size/L
