Repository kubeflow/code-intelligence, pull requests merged in 2019-09, with the labels that each got.

#48 Updated README.md
  Issue_Embeddings/README.md
Labels: cla: yes, size/M

#49 Cleanup README.md
  Issue_Embeddings/README.md
Labels: approved, cla: yes, lgtm, size/XS

#47 Code refactoring to add gcs & pubsub utils
  py/code_intelligence/gcs_util.py
  py/code_intelligence/pubsub_util.py
  py/label_microservice/worker.py
Labels: approved, cla: yes, lgtm, size/L

#50 Fix needs triage; kind labels should have kind prefix.
  Issue_Triage/notebooks/triage.ipynb
  py/issue_triage/triage.py
Labels: approved, cla: yes, lgtm, size/XXL

#51 Add readme to label microservice
  Label_Microservice/README.md
  Label_Microservice/docs/onboarding_new_repositories.md
  Label_Microservice/docs/set_up_staging_cluster.md
  Label_Microservice/images/rollout.png
Labels: approved, cla: yes, lgtm, size/XL

#53 Check in the batch code.
  py/code_intelligence/embeddings.py
  py/code_intelligence/inference.py
Labels: approved, cla: yes, lgtm, size/M

#54 Clean up notebooks and rebuild fairing images.
  Label_Microservice/notebooks/Training_Pipeline.ipynb
  Label_Microservice/notebooks/issues_loader.ipynb
  Label_Microservice/notebooks/repo_mlp.ipynb
Labels: approved, cla: yes, lgtm, size/L
